apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: osm-mstream-nginx-cm
data:  
  nginx.conf: |
    events {
    worker_connections  4096;  ## Default: 1024
    }
    http {
      server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
        }
      }
    }