apiVersion: v1
kind: Service
metadata:
  name: osm-mstream
  labels:
    app: osm-mstream
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      name: ssh
      protocol: TCP
    - port: 3000
      targetPort: app
      name: app
      protocol: TCP
  selector:
    name: osm-mstream